import { MainLayout } from '@/components/MainLayout';
import { AppProvider } from '@/providers';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='ja'>
      <body>
        <AppProvider>
          <MainLayout>{children}</MainLayout>
        </AppProvider>
      </body>
    </html>
  );
};
export default RootLayout;
