import { ReactNode } from 'react';

import { MainLayout } from '@/components/MainLayout';
import { AppProvider } from '@/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="ja">
    <body>
      <AppProvider>
        <MainLayout>{children}</MainLayout>
      </AppProvider>
    </body>
  </html>
);
export default RootLayout;
