import { ReactNode } from 'react';

import { MainLayout } from '@/components/mainLayout';
import AppProvider from '@/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false, // noindexの設定
  },
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="ja">
    <body>
      <AppProvider>
        <MainLayout>{children}</MainLayout>
      </AppProvider>
      {children}
    </body>
  </html>
);
export default RootLayout;
